import React from 'react';
import './App.css';
import Characters from '../Characters/Characters';
import Bodies from '../Bodies/Bodies';
import Wheels from '../Wheels/Wheels';
import Gliders from '../Gliders/Gliders';
import Statistics from '../Statistics/Statistics';

class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            characters:     [       { name:'Mario', landSpeed: 3.75, antiGravitySpeed: 3.5, waterSpeed: 4, airSpeed: 4.25, acceleration: 3.5, weight:                         3.5, landHandling: 3.5, antiGravityHandling: 3.5, waterHandling: 3, airHandling: 3.5, traction: 3.5, miniTurbo:                           3.25, src: 'https://i.postimg.cc/fb0ZCzxD/Mario.png' } ,
                                    { name:'Luigi', landSpeed: 3.75, antiGravitySpeed: 3.5, waterSpeed: 4, airSpeed: 4.25, acceleration: 3.5, weight: 3.5, landHandling: 3.75, antiGravityHandling: 3.75, waterHandling: 3.25, airHandling: 3.75, traction: 3.25, miniTurbo: 3.25, src: 'https://i.postimg.cc/TwMxHz9m/Luigi.png' } ,
                                    { name:'Peach', landSpeed: 3.5, antiGravitySpeed: 3.25, waterSpeed: 3.75, airSpeed: 4, acceleration: 3.75, weight: 3, landHandling: 3.75, antiGravityHandling: 3.75, waterHandling: 3.25, airHandling: 3.75, traction: 3.75, miniTurbo: 3.5, src: 'https://i.postimg.cc/CLLgtHjv/Peach.png' } ,
                                    { name:'Daisy', landSpeed: 3.5, antiGravitySpeed: 3.25, waterSpeed: 3.75, airSpeed: 4, acceleration: 3.75, weight: 3, landHandling: 3.75, antiGravityHandling: 3.75, waterHandling: 3.25, airHandling: 3.75, traction: 3.75, miniTurbo: 3.5, src: 'https://i.postimg.cc/qR3RNcmc/Daisy.png' } ,
                                    { name:'Rosalina', landSpeed: 4, antiGravitySpeed: 3.75, waterSpeed: 4.25, airSpeed: 4.5, acceleration: 3.25, weight: 3.75, landHandling: 3.25, antiGravityHandling: 3.25, waterHandling: 2.75, airHandling: 3.25, traction: 3.75, miniTurbo: 3.25, src: 'https://i.postimg.cc/htXq4DZT/Rosalina.png' } ,
                                    { name:'Tanooki Mario', landSpeed: 3.5, antiGravitySpeed: 3.25, waterSpeed: 3.75, airSpeed: 4, acceleration: 3.75, weight: 3.25, landHandling: 3.75, antiGravityHandling: 3.75, waterHandling: 3.25, airHandling: 3.75, traction: 3.25, miniTurbo: 3.5, src: 'https://i.postimg.cc/cHSqcQxB/Tanuki-Mario.png' } ,
                                    { name:'Cat Peach', landSpeed: 3.25, antiGravitySpeed: 3, waterSpeed: 3.5, airSpeed: 3.75, acceleration: 4, weight: 2.75, landHandling: 4, antiGravityHandling: 4, waterHandling: 3.5, airHandling: 4, traction: 3.75, miniTurbo: 3.5, src: 'https://i.postimg.cc/6qVp0Wxy/Cat-Peach.png' } ,
                                    { name:'Yoshi', landSpeed: 3.5, antiGravitySpeed: 3.25, waterSpeed: 3.75, airSpeed: 4, acceleration: 3.75, weight: 3, landHandling: 3.75, antiGravityHandling: 3.75, waterHandling: 3.25, airHandling: 3.75, traction: 3.75, miniTurbo: 3.5, src: 'https://i.postimg.cc/T3LZMkhc/Yoshi.png' } ,
                                    { name:'Toad', landSpeed: 3, antiGravitySpeed: 2.75, waterSpeed: 3.25, airSpeed: 3.5, acceleration: 4, weight: 2.75, landHandling: 4.25, antiGravityHandling: 4.25, waterHandling: 3.75, airHandling: 4.25, traction: 4, miniTurbo: 3.5, src: 'https://i.postimg.cc/0QdTXbrR/Toad.png' } ,
                                    { name:'Koopa Troopa', landSpeed: 2.75, antiGravitySpeed: 2.5, waterSpeed: 3, airSpeed: 3.25, acceleration: 4, weight: 2.5, landHandling: 4.5, antiGravityHandling: 4.5, waterHandling: 4, airHandling: 4.5, traction: 4.25, miniTurbo: 3.75, src: 'https://i.postimg.cc/XNKjtYtv/Koopa-Troopa.png' } ,
                                    { name:'Shy Guy', landSpeed: 3, antiGravitySpeed: 2.75, waterSpeed: 3.25, airSpeed: 3.5, acceleration: 4, weight: 2.75, landHandling: 4.25, antiGravityHandling: 4.25, waterHandling: 3.75, airHandling: 4.25, traction: 4, miniTurbo: 3.5, src: 'https://i.postimg.cc/R0f5fPB0/Shy-Guy.png' } ,
                                    { name:'Lakitu', landSpeed: 2.75, antiGravitySpeed: 2.5, waterSpeed: 3, airSpeed: 3.25, acceleration: 4, weight: 2.5, landHandling: 4.5, antiGravityHandling: 4.5, waterHandling: 4, airHandling: 4.5, traction: 4.25, miniTurbo: 3.75, src: 'https://i.postimg.cc/dtqsFKKj/Lakitu.png' } ,
                                    { name:'Toadette', landSpeed: 2.75, antiGravitySpeed: 2.5, waterSpeed: 3, airSpeed: 3.25, acceleration: 4.25, weight: 2.5, landHandling: 4.25, antiGravityHandling: 4.25, waterHandling: 3.75, airHandling: 4.25, traction: 3.5, miniTurbo: 3.75, src: 'https://i.postimg.cc/KjGd6xgK/Toadette.png' } ,
                                    { name:'King Boo', landSpeed: 4, antiGravitySpeed: 3.75, waterSpeed: 4.25, airSpeed: 4.5, acceleration: 3.25, weight: 3.75, landHandling: 3.25, antiGravityHandling: 3.25, waterHandling: 2.75, airHandling: 3.25, traction: 3.75, miniTurbo: 3.25, src: 'https://i.postimg.cc/HxXYYYxB/King-Boo.png' } ,
                                    { name:'Baby Mario', landSpeed: 2.5, antiGravitySpeed: 2.25, waterSpeed: 2.75, airSpeed: 3, acceleration: 4.25, weight: 2.25, landHandling: 4.5, antiGravityHandling: 4.5, waterHandling: 4, airHandling: 4.5, traction: 4, miniTurbo: 3.75, src: 'https://i.postimg.cc/nh3Mghjm/Baby-Mario.png' } ,
                                    { name:'Baby Luigi', landSpeed: 2.5, antiGravitySpeed: 2.25, waterSpeed: 2.75, airSpeed: 3, acceleration: 4.25, weight: 2.25, landHandling: 4.5, antiGravityHandling: 4.5, waterHandling: 4, airHandling: 4.5, traction: 4, miniTurbo: 3.75, src: 'https://i.postimg.cc/vHL47zG3/Baby-Luigi.png' } ,
                                    { name:'Baby Peach', landSpeed: 2.25, antiGravitySpeed: 2, waterSpeed: 2.5, airSpeed: 2.75, acceleration: 4, weight: 2, landHandling: 5, antiGravityHandling: 5, waterHandling: 4.5, airHandling: 5, traction: 4.25, miniTurbo: 4, src: 'https://i.postimg.cc/dVsL5y1v/Baby-Peach.png'} ,
                                    { name:'Baby Daisy', landSpeed: 2.25, antiGravitySpeed: 2, waterSpeed: 2.5, airSpeed: 2.75, acceleration: 4, weight: 2, landHandling: 5, antiGravityHandling: 5, waterHandling: 4.5, airHandling: 5, traction: 4.25, miniTurbo: 4, src: 'https://i.postimg.cc/HsCJ7K1r/Baby-Daisy.png'} ,
                                    { name:'Baby Rosalina', landSpeed: 2.25, antiGravitySpeed: 2, waterSpeed: 2.5, airSpeed: 2.75, acceleration: 4.25, weight: 2, landHandling: 4.75, antiGravityHandling: 4.75, waterHandling: 4.25, airHandling: 4.75, traction: 3.75, miniTurbo: 4, src: 'https://i.postimg.cc/g0rrWb8T/Baby-Rosalina.png'} ,
                                    { name:'Metal Mario', landSpeed: 4.25, antiGravitySpeed: 4, waterSpeed: 4.5, airSpeed: 4.75, acceleration: 3.25, weight: 4.5, landHandling: 3.25, antiGravityHandling: 3.25, waterHandling: 2.75, airHandling: 3.25, traction: 3.25, miniTurbo: 3, src: 'https://i.postimg.cc/PJdjd105/Metal-Mario.png' } ,
                                    { name:'Pink Gold Peach', landSpeed: 4.25, antiGravitySpeed: 4, waterSpeed: 4.5, airSpeed: 4.75, acceleration: 3.25, weight: 4.5, landHandling: 3.25, antiGravityHandling: 3.25, waterHandling: 2.75, airHandling: 3.25, traction: 3.25, miniTurbo: 3, src: 'https://i.postimg.cc/DyjTKJ67/Pink-Gold-Peach.png' } ,
                                    { name:'Wario', landSpeed: 4.75, antiGravitySpeed: 4.5, waterSpeed: 5, airSpeed: 5.25, acceleration: 3, weight: 4.25, landHandling: 2.75, antiGravityHandling: 2.75, waterHandling: 2.25, airHandling: 2.75, traction: 3.25, miniTurbo: 2.75, src: 'https://i.postimg.cc/7YLFXPkd/Wario.png' } ,
                                    { name:'Waluigi', landSpeed: 4.5, antiGravitySpeed: 4.25, waterSpeed: 4.75, airSpeed: 5, acceleration: 3.25, weight: 4, landHandling: 3, antiGravityHandling: 3, waterHandling: 2.5, airHandling: 3, traction: 3, miniTurbo: 3, src: 'https://i.postimg.cc/CMJyjBWb/Waluigi.png' } ,
                                    { name:'Donkey Kong', landSpeed: 4.5, antiGravitySpeed: 4.25, waterSpeed: 4.75, airSpeed: 5, acceleration: 3.25, weight: 4, landHandling: 3, antiGravityHandling: 3, waterHandling: 2.5, airHandling: 3, traction: 3, miniTurbo: 3, src: 'https://i.postimg.cc/44pyZ5Hs/Donkey-Kong.png' } ,
                                    { name:'Bowser', landSpeed: 4.75, antiGravitySpeed: 4.5, waterSpeed: 5, airSpeed: 5.25, acceleration: 3, weight: 4.5, landHandling: 2.5, antiGravityHandling: 2.5, waterHandling: 2, airHandling: 2.5, traction: 3, miniTurbo: 2.75, src: 'https://i.postimg.cc/cJjC1kc4/Bowser.png' } ,
                                    { name:'Dry Bones', landSpeed: 2.5, antiGravitySpeed: 2.25, waterSpeed: 2.75, airSpeed: 3, acceleration: 4.25, weight: 2.25, landHandling: 4.5, antiGravityHandling: 4.5, waterHandling: 4, airHandling: 4.5, traction: 4, miniTurbo: 3.75, src: 'https://i.postimg.cc/02xQNw7m/Dry-Bones.png' } ,
                                    { name:'Bowser Jr.', landSpeed: 2.75, antiGravitySpeed: 2.5, waterSpeed: 3, airSpeed: 3.25, acceleration: 4, weight: 2.5, landHandling: 4.5, antiGravityHandling: 4.5, waterHandling: 4, airHandling: 4.5, traction: 4.25, miniTurbo: 3.75, src: 'https://i.postimg.cc/d3c0r7Xb/BowserJr.png' } ,
                                    { name:'Dry Bowser', landSpeed: 4.75, antiGravitySpeed: 4.5, waterSpeed: 5, airSpeed: 5.25, acceleration: 3, weight: 4.25, landHandling: 2.75, antiGravityHandling: 2.75, waterHandling: 2.25, airHandling: 2.75, traction: 3.25, miniTurbo: 2.75, src: 'https://i.postimg.cc/VLRN0kFh/Dry-Bowser.png' } ,
                                    { name:'Lemmy', landSpeed: 2.25, antiGravitySpeed: 2, waterSpeed: 2.5, airSpeed: 2.75, acceleration: 4.25, weight: 2, landHandling: 4.75, antiGravityHandling: 4.75, waterHandling: 4.25, airHandling: 4.75, traction: 3.75, miniTurbo: 4, src: 'https://i.postimg.cc/YC0t4f04/Lemmy.png' } ,
                                    { name:'Larry', landSpeed: 3, antiGravitySpeed: 2.75, waterSpeed: 3.25, airSpeed: 3.5, acceleration: 4, weight: 2.75, landHandling: 4.25, antiGravityHandling: 4.25, waterHandling: 3.75, airHandling: 4.25, traction: 4, miniTurbo: 3.5, src: 'https://i.postimg.cc/xTt0TFfD/Larry.png' } ,
                                    { name:'Wendy', landSpeed: 2.75, antiGravitySpeed: 2.5, waterSpeed: 3, airSpeed: 3.25, acceleration: 4.25, weight: 2.5, landHandling: 4.25, antiGravityHandling: 4.25, waterHandling: 3.75, airHandling: 4.25, traction: 3.5, miniTurbo: 3.75, src: 'https://i.postimg.cc/SNtwP0Qs/Wendy.png' } ,
                                    { name:'Ludwig', landSpeed: 3.75, antiGravitySpeed: 3.5, waterSpeed: 4, airSpeed: 4.25, acceleration: 3.5, weight: 3.5, landHandling: 3.5, antiGravityHandling: 3.5, waterHandling: 3, airHandling: 3.5, traction: 3.5, miniTurbo: 3.25, src: 'https://i.postimg.cc/mDY4xmXn/Ludwig.png' } ,
                                    { name:'Iggy', landSpeed: 3.75, antiGravitySpeed: 3.5, waterSpeed: 4, airSpeed: 4.25, acceleration: 3.5, weight: 3.5, landHandling: 3.75, antiGravityHandling: 3.75, waterHandling: 3.25, airHandling: 3.75, traction: 3.25, miniTurbo: 3.25, src: 'https://i.postimg.cc/DzWfNdKV/Iggy.png' } ,
                                    { name:'Roy', landSpeed: 4.5, antiGravitySpeed: 4.25, waterSpeed: 4.75, airSpeed: 5, acceleration: 3.25, weight: 4, landHandling: 3, antiGravityHandling: 3, waterHandling: 2.5, airHandling: 3, traction: 3, miniTurbo: 3, src: 'https://i.postimg.cc/8zxgj2x3/Roy.png' } ,
                                    { name:'Morton', landSpeed: 4.75, antiGravitySpeed: 4.5, waterSpeed: 5, airSpeed: 5.25, acceleration: 3, weight: 4.5, landHandling: 2.5, antiGravityHandling: 2.5, waterHandling: 2, airHandling: 2.5, traction: 3, miniTurbo: 2.75, src: 'https://i.postimg.cc/c1cWX58g/Morton.png' } ,
                                    { name:'Inkling Girl', landSpeed: 3.25, antiGravitySpeed: 3, waterSpeed: 3.5, airSpeed: 3.75, acceleration: 4, weight: 2.75, landHandling: 4, antiGravityHandling: 4, waterHandling: 3.5, airHandling: 4, traction: 3.75, miniTurbo: 3.5, src: 'https://i.postimg.cc/1XKyFvDF/Inkling-Girl.png' } ,
                                    { name:'Inkling Boy', landSpeed: 3.5, antiGravitySpeed: 3.25, waterSpeed: 3.75, airSpeed: 4, acceleration: 3.75, weight: 3.25, landHandling: 3.75, antiGravityHandling: 3.75, waterHandling: 3.25, airHandling: 3.75, traction: 3.25, miniTurbo: 3.5, src: 'https://i.postimg.cc/HLfW1cpr/Inkling-Boy.png' } ,
                                    { name:'Link', landSpeed: 4, antiGravitySpeed: 3.75, waterSpeed: 4.25, airSpeed: 4.5, acceleration: 3.25, weight: 3.75, landHandling: 3.25, antiGravityHandling: 3.25, waterHandling: 2.75, airHandling: 3.25, traction: 3.75, miniTurbo: 3.25, src: 'https://i.postimg.cc/0y4P7MKV/Link.png' } ,
                                    { name:'Male Villager', landSpeed: 3.5, antiGravitySpeed: 3.25, waterSpeed: 3.75, airSpeed: 4, acceleration: 3.75, weight: 3.25, landHandling: 3.75, antiGravityHandling: 3.75, waterHandling: 3.25, airHandling: 3.75, traction: 3.25, miniTurbo: 3.5, src: 'https://i.postimg.cc/x86WYhK6/Villager.png' } ,
                                    { name:'Female Villager', landSpeed: 3.25, antiGravitySpeed: 3, waterSpeed: 3.5, airSpeed: 3.75, acceleration: 4, weight: 2.75, landHandling: 4, antiGravityHandling: 4, waterHandling: 3.5, airHandling: 4, traction: 3.75, miniTurbo: 3.5, src: 'https://i.postimg.cc/1333G1C3/Female-Villager.png' } ,
                                    { name:'Isabella', landSpeed: 2.75, antiGravitySpeed: 2.5, waterSpeed: 3, airSpeed: 3.25, acceleration: 4.25, weight: 2.5, landHandling: 4.25, antiGravityHandling: 4.25, waterHandling: 3.75, airHandling: 4.25, traction: 3.5, miniTurbo: 3.75, src: 'https://i.postimg.cc/WzV2tBqj/Isabella.png' } ,
                                    { name:'Light Mii', landSpeed: 2.5, antiGravitySpeed: 2.25, waterSpeed: 2.75, airSpeed: 3, acceleration: 4.25, weight: 2.25, landHandling: 4.5, antiGravityHandling: 4.5, waterHandling: 4, airHandling: 4.5, traction: 4, miniTurbo: 3.75, src: 'https://i.postimg.cc/L4Y4JLpB/Light-Mii.png' } ,
                                    { name:'Medium Mii', landSpeed: 3.75, antiGravitySpeed: 3.5, waterSpeed: 4, airSpeed: 4.25, acceleration: 3.5, weight: 3.5, landHandling: 3.5, antiGravityHandling: 3.5, waterHandling: 3, airHandling: 3.5, traction: 3.5, miniTurbo: 3.25, src: 'https://i.postimg.cc/c4fsmW6v/Medium-Mii.png' } ,
                                    { name:'Heavy Mii', landSpeed: 4.75, antiGravitySpeed: 4.5, waterSpeed: 5, airSpeed: 5.25, acceleration: 3, weight: 4.5, landHandling: 2.5, antiGravityHandling: 2.5, waterHandling: 2, airHandling: 2.5, traction: 3, miniTurbo: 2.75, src: 'https://i.postimg.cc/gcCz8jc9/Heavy-Mii.png' }
                        ] ,
            bodies:     [           { name:'Standard Kart', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight:                           0,  landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src:                           'https://i.postimg.cc/nLc0BJP2/Standard-Kart.png' } ,
                                    { name:'Pipe Frame', landSpeed: -0.5, antiGravitySpeed: -0.5, waterSpeed: 0, airSpeed: -0.5, acceleration: 0.5, weight: -0.25, landHandling: 0.5, antiGravityHandling: 0.25, waterHandling: 0.5, airHandling: -0.25, traction: 0.25, miniTurbo: 0.5, src: 'https://i.postimg.cc/XNZ1sn7D/Pipe-Frame.png' } ,
                                    { name:'Mach 8', landSpeed: 0, antiGravitySpeed: 0.5, waterSpeed: 0, airSpeed: 0.25, acceleration: -0.25, weight: 0.25, landHandling: -0.25, antiGravityHandling: 0.25, waterHandling: 0, airHandling: -0.25, traction: 0.25, miniTurbo: 0, src: 'https://i.postimg.cc/d0qGpjRV/Mach-8.png' } ,
                                    { name:'Steel Driver', landSpeed: 0.25, antiGravitySpeed: -0.25, waterSpeed: 0.5, airSpeed: -0.75, acceleration: -0.75, weight: 0.5, landHandling: -0.5, antiGravityHandling: -0.5, waterHandling: 0.75, airHandling: -0.5, traction: 0, miniTurbo: -0.5, src: 'https://i.postimg.cc/9MDbgBVq/Steel-Driver.png' } ,
                                    { name:'Cat Cruiser', landSpeed: -0.25, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: 0.25, acceleration: 0.25, weight: 0, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0, airHandling: 0.25, traction: 0, miniTurbo: 0.25, src: 'https://i.postimg.cc/bN7TCnFZ/Cat-Cruiser.png' } ,
                                    { name:'Circuit Special', landSpeed: 0.5, antiGravitySpeed: 0.25, waterSpeed: -0.5, airSpeed: -0.25, acceleration: -0.75, weight: 0.25, landHandling: -0.5, antiGravityHandling: -0.25, waterHandling: -0.25, airHandling: -0.75, traction: -0.5, miniTurbo: -0.75, src: 'https://i.postimg.cc/25mxmDYm/Circuit-Special.png' } ,
                                    { name:'Tri-Speeder', landSpeed: 0.25, antiGravitySpeed: -0.25, waterSpeed: 0.5, airSpeed: -0.75, acceleration: -0.75, weight: 0.5, landHandling: -0.5, antiGravityHandling: -0.5, waterHandling: 0.75, airHandling: -0.5, traction: 0, miniTurbo: -0.5, src: 'https://i.postimg.cc/65JczRPy/Tri-Speeder.png' } ,
                                    { name:'Badwagon', landSpeed: 0.5, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: -0.5, acceleration: -1, weight: 0.5, landHandling: -0.75, antiGravityHandling: -0.5, waterHandling: -0.25, airHandling: -0.75, traction: 0.5, miniTurbo: -1, src: 'https://i.postimg.cc/Zn0cgxSd/Badwagon.png' } ,
                                    { name:'Prancer', landSpeed: 0.25, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: -0.5, weight: -0.25, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0, traction: -0.25, miniTurbo: -0.25, src: 'https://i.postimg.cc/MHjBVPwd/Prancer.png' } ,
                                    { name:'Biddybuggy', landSpeed: -0.75, antiGravitySpeed: -0.25, waterSpeed: -0.5, airSpeed: -0.5, acceleration: 0.75, weight: -0.5, landHandling: 0.5, antiGravityHandling: 0.5, waterHandling: 0.5, airHandling: 0.25, traction: 0.25, miniTurbo: 0.75, src: 'https://i.postimg.cc/h43Mm6Lb/Biddybuggy.png' } ,
                                    { name:'Landship', landSpeed: -0.5, antiGravitySpeed: -0.75, waterSpeed: 0.5, airSpeed: -0.25, acceleration: 0.5, weight: -0.5, landHandling: 0.25, antiGravityHandling: -0.25, waterHandling: 0.75, airHandling: 0, traction: 0.75, miniTurbo: 0.5, src: 'https://i.postimg.cc/Hk0Q6hyN/Landship.png' } ,
                                    { name:'Sneeker', landSpeed: 0.25, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: 0, acceleration: -0.5, weight: 0, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: -0.25, traction: -0.75, miniTurbo: -0.25, src: 'https://i.postimg.cc/R0TCpj4N/Sneeker.png' } ,
                                    { name:'Sports Coupe', landSpeed: 0, antiGravitySpeed: 0.5, waterSpeed: 0, airSpeed: 0.25, acceleration: -0.25, weight: 0.25, landHandling: -0.25, antiGravityHandling: 0.25, waterHandling: 0, airHandling: -0.25, traction: 0.25, miniTurbo: 0, src: 'https://i.postimg.cc/cLWD1Y7V/Sport-Coupe.png' } ,
                                    { name:'Gold Standard', landSpeed: 0.25, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: 0, acceleration: -0.5, weight: 0, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: -0.25, traction: -0.75, miniTurbo: -0.25, src: 'https://i.postimg.cc/4d2vzH9N/Gold-Standard.png' } ,
                                    { name:'GLA ', landSpeed: 0.5, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: -0.5, acceleration: -1, weight: 0.5, landHandling: -0.75, antiGravityHandling: -0.5, waterHandling: -0.25, airHandling: -0.75, traction: 0.5, miniTurbo: -1, src: 'https://i.postimg.cc/9XSt0T2L/GLA.png' } ,
                                    { name:'W 25 Silver Arrow', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: 0.25, weight: -0.25, landHandling: 0.25, antiGravityHandling: 0.25, waterHandling: 0.25, airHandling: 0, traction: 0.5, miniTurbo: 0.25, src: 'https://i.postimg.cc/mgTwW4B4/W-25-Silver-Arrow.png' } ,
                                    { name:'300 SL Roadster', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src: 'https://i.postimg.cc/ZRwHVD1m/300-SL-Roadster.png' } ,
                                    { name:'Blue Falcon', landSpeed: 0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: -0.25, weight: -0.5, landHandling: -0.25, antiGravityHandling: 0.5, waterHandling: 0.25, airHandling: -0.5, traction: 0, miniTurbo: -0.25, src: 'https://i.postimg.cc/rw59vpvQ/Blue-Falcon.png' } ,
                                    { name:'Tanooki Kart', landSpeed: -0.25, antiGravitySpeed: 0, waterSpeed: 0.25, airSpeed: 0, acceleration: -0.5, weight: 0.25, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0.5, airHandling: 0, traction: 1, miniTurbo: -0.25, src: 'https://i.postimg.cc/x8HRnTXf/Tanooki-Kart.png' } ,
                                    { name:'B-Dasher', landSpeed: 0.5, antiGravitySpeed: 0.25, waterSpeed: -0.5, airSpeed: -0.25, acceleration: -0.75, weight: 0.25, landHandling: -0.5, antiGravityHandling: -0.25, waterHandling: -0.25, airHandling: -0.75, traction: -0.5, miniTurbo: -0.75, src: 'https://i.postimg.cc/T1S9X5dH/B-Dasher.png' } ,
                                    { name:'Streetle', landSpeed: -0.5, antiGravitySpeed: -0.75, waterSpeed: 0.5, airSpeed: -0.25, acceleration: 0.5, weight: -0.5, landHandling: 0.25, antiGravityHandling: -0.25, waterHandling: 0.75, airHandling: 0, traction: 0.75, miniTurbo: 0.5, src: 'https://i.postimg.cc/pdGkBSNH/Streetle.png' } ,
                                    { name:'P-Wing', landSpeed: 0.5, antiGravitySpeed: 0.25, waterSpeed: -0.5, airSpeed: -0.25, acceleration: -0.75, weight: 0.25, landHandling: -0.5, antiGravityHandling: -0.25, waterHandling: -0.25, airHandling: -0.75, traction: -0.5, miniTurbo: -0.75, src: 'https://i.postimg.cc/nzW7s8yX/P-Wing.png' } ,
                                    { name:'Koopa Clown', landSpeed: -0.25, antiGravitySpeed: 0, waterSpeed: 0.25, airSpeed: 0, acceleration: -0.5, weight: 0.25, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0.5, airHandling: 0, traction: 1, miniTurbo: -0.25, src: 'https://i.postimg.cc/kgPQFmB8/Koopa-Clown.png' } ,
                                    { name:'Standard Bike', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: 0.25, weight: -0.25, landHandling: 0.25, antiGravityHandling: 0.25, waterHandling: 0.25, airHandling: 0, traction: 0.5, miniTurbo: 0.25, src: 'https://i.postimg.cc/MpY9nTdX/Standard-Bike.png' } ,
                                    { name:'Comet ', landSpeed: -0.25, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: 0.25, acceleration: 0.25, weight: 0, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0, airHandling: 0.25, traction: 0, miniTurbo: 0.25, src: 'https://i.postimg.cc/RFZQ6LqD/Comet.png' } ,
                                    { name:'Sport Bike', landSpeed: 0.25, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: -0.5, weight: -0.25, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0, traction: -0.25, miniTurbo: -0.25, src: 'https://i.postimg.cc/66DjSF86/Sport-Bike.png' } ,
                                    { name:'The Duke', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src: 'https://i.postimg.cc/BQTgzbWN/The-Duke.png' } ,
                                    { name:'Flame Rider', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: 0.25, weight: -0.25, landHandling: 0.25, antiGravityHandling: 0.25, waterHandling: 0.25, airHandling: 0, traction: 0.5, miniTurbo: 0.25, src: 'https://i.postimg.cc/PJBm7Gyg/Flame-Rider.png' } ,
                                    { name:'Varmint ', landSpeed: -0.5, antiGravitySpeed: -0.5, waterSpeed: 0, airSpeed: -0.5, acceleration: 0.5, weight: -0.25, landHandling: 0.5, antiGravityHandling: 0.25, waterHandling: 0.5, airHandling: -0.25, traction: 0.25, miniTurbo: 0.5, src: 'https://i.postimg.cc/1zjcFN6R/Varmint.png' } ,
                                    { name:'Mr Scooty', landSpeed: -0.75, antiGravitySpeed: -0.25, waterSpeed: -0.5, airSpeed: -0.5, acceleration: 0.75, weight: -0.5, landHandling: 0.5, antiGravityHandling: 0.5, waterHandling: 0.5, airHandling: 0.25, traction: 0.25, miniTurbo: 0.75, src: 'https://i.postimg.cc/9M0ZFXn3/Mr-Scooty.png' } ,
                                    { name:'Jet Bike', landSpeed: 0.25, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: -0.5, weight: -0.25, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0, traction: -0.25, miniTurbo: -0.25, src: 'https://i.postimg.cc/Y046826N/Jet-Bike.png' } ,
                                    { name:'Yoshi Bike', landSpeed: -0.25, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: 0.25, acceleration: 0.25, weight: 0, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0, airHandling: 0.25, traction: 0, miniTurbo: 0.25, src: 'https://i.postimg.cc/YC8xpPCW/Yoshi-Bike.png' } ,
                                    { name:'Master Cycle', landSpeed: 0.25, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: 0, acceleration: -0.5, weight: 0, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: -0.25, traction: -0.75, miniTurbo: -0.25, src: 'https://i.postimg.cc/3wn2T09C/Master-Cycle.png' } ,
                                    { name:'Master Cycle Zero', landSpeed: -0.25, antiGravitySpeed: 0, waterSpeed: 0.25, airSpeed: 0, acceleration: -0.5, weight: 0.25, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0.5, airHandling: 0, traction: 1, miniTurbo: -0.25, src: 'https://i.postimg.cc/23RZwQ8m/Master-Cycle-Zero.png' } ,
                                    { name:'City Tripper', landSpeed: -0.5, antiGravitySpeed: -0.5, waterSpeed: 0, airSpeed: -0.5, acceleration: 0.5, weight: -0.25, landHandling: 0.5, antiGravityHandling: 0.25, waterHandling: 0.5, airHandling: -0.25, traction: 0.25, miniTurbo: 0.5, src: 'https://i.postimg.cc/KYND8HcT/City-Tripper.png' } ,
                                    { name:'Standard ATV', landSpeed: 0.5, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: -0.5, acceleration: -1, weight: 0.5, landHandling: -0.75, antiGravityHandling: -0.5, waterHandling: -0.25, airHandling: -0.75, traction: 0.5, miniTurbo: -1, src: 'https://i.postimg.cc/3RzBsDJf/Standard-ATV.png' } ,
                                    { name:'Wild Wiggler', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: 0.25, weight: -0.25, landHandling: 0.25, antiGravityHandling: 0.25, waterHandling: 0.25, airHandling: 0, traction: 0.5, miniTurbo: 0.25, src: 'https://i.postimg.cc/9fMYzBDN/Wild-Wiggler.png' } ,
                                    { name:'Teddy Buggy', landSpeed: -0.25, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: 0.25, acceleration: 0.25, weight: 0, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0, airHandling: 0.25, traction: 0, miniTurbo: 0.25, src: 'https://i.postimg.cc/8krwhwt2/Teddy-Buggy.png' } ,
                                    { name:'Bone Rattler', landSpeed: 0.25, antiGravitySpeed: -0.25, waterSpeed: 0.5, airSpeed: -0.75, acceleration: -0.75, weight: 0.5, landHandling: -0.5, antiGravityHandling: -0.5, waterHandling: 0.75, airHandling: -0.5, traction: 0, miniTurbo: -0.5, src: 'https://i.postimg.cc/Hscz9z3G/Bone-Rattler.png' } ,
                                    { name:'Splat Buggy', landSpeed: 0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: -0.25, weight: -0.5, landHandling: -0.25, antiGravityHandling: 0.5, waterHandling: 0.25, airHandling: -0.5, traction: 0, miniTurbo: -0.25, src: 'https://i.postimg.cc/wTLfdFNX/Splat-Buggy.png' } ,
                                    { name:'Inkstriker', landSpeed: 0, antiGravitySpeed: 0.5, waterSpeed: 0, airSpeed: 0.25, acceleration: -0.25, weight: 0.25, landHandling: -0.25, antiGravityHandling: 0.25, waterHandling: 0, airHandling: -0.25, traction: 0.25, miniTurbo: 0, src: 'https://i.postimg.cc/15q0qt5s/Inkstriker.png' }
                        ] ,
            wheels:     [           { name:'Standard', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0,                             landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src:                               'https://i.postimg.cc/ZKMnPFnd/Standard.png' } ,
                                    { name:'Monster', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: -0.5, acceleration: -0.5, weight: 0.5, landHandling: -0.75, antiGravityHandling: -0.75, waterHandling: -0.5, airHandling: -0.5, traction: 0.5, miniTurbo: -0.25, src: 'https://i.postimg.cc/g21wpqPW/Monster.png' } ,
                                    { name:'Roller', landSpeed: -0.5, antiGravitySpeed: -0.5, waterSpeed: 0, airSpeed: 0, acceleration: 0.5, weight: -0.5, landHandling: 0.25, antiGravityHandling: 0.25, waterHandling: 0.25, airHandling: 0.25, traction: -0.25, miniTurbo: 0.75, src: 'https://i.postimg.cc/V6W5Xx0f/Roller.png' } ,
                                    { name:'Slim', landSpeed: 0.25, antiGravitySpeed: 0.5, waterSpeed: -0.25, airSpeed: -0.25, acceleration: -0.5, weight: 0, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0.25, airHandling: 0.25, traction: -1, miniTurbo: -0.25, src: 'https://i.postimg.cc/c4H685xW/Slim.png' } ,
                                    { name:'Slick', landSpeed: 0.5, antiGravitySpeed: 0.5, waterSpeed: -0.75, airSpeed: -0.75, acceleration: -0.75, weight: 0.25, landHandling: -0.25, antiGravityHandling: -0.25, waterHandling: -0.75, airHandling: -0.5, traction: -1.25, miniTurbo: -0.75, src: 'https://i.postimg.cc/Df580KK5/Slick.png' } ,
                                    { name:'Metal', landSpeed: 0.5, antiGravitySpeed: -0.25, waterSpeed: 0, airSpeed: -0.25, acceleration: -1, weight: 0.5, landHandling: -0.25, antiGravityHandling: -0.5, waterHandling: -0.25, airHandling: -0.75, traction: -0.75, miniTurbo: -0.75, src: 'https://i.postimg.cc/RZW32pyd/Metal.png' } ,
                                    { name:'Button', landSpeed: -0.25, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: -0.25, acceleration: 0.25, weight: -0.5, landHandling: 0, antiGravityHandling: 0.25, waterHandling: 0, airHandling: -0.25, traction: -0.5, miniTurbo: 0.5, src: 'https://i.postimg.cc/g06ZLtKj/Button.png' } ,
                                    { name:'Off-Road', landSpeed: 0.25, antiGravitySpeed: 0, waterSpeed: 0.25, airSpeed: -0.5, acceleration: -0.25, weight: 0.25, landHandling: -0.5, antiGravityHandling: -0.25, waterHandling: -0.5, airHandling: -0.5, traction: 0.25, miniTurbo: -0.5, src: 'https://i.postimg.cc/HxgVcYxv/Off-Road.png' } ,
                                    { name:'Sponge', landSpeed: -0.25, antiGravitySpeed: -0.25, waterSpeed: -0.5, airSpeed: 0.25, acceleration: 0, weight: -0.25, landHandling: -0.25, antiGravityHandling: 0, waterHandling: -0.5, airHandling: 0, traction: 0.25, miniTurbo: 0.25, src: 'https://i.postimg.cc/sxfxmT5p/Sponge.png' } ,
                                    { name:'Wood', landSpeed: 0.25, antiGravitySpeed: 0.5, waterSpeed: -0.25, airSpeed: -0.25, acceleration: -0.5, weight: 0, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0.25, airHandling: 0.25, traction: -1, miniTurbo: -0.25, src: 'https://i.postimg.cc/25p5Mk4j/Wood.png' } ,
                                    { name:'Cushion', landSpeed: -0.25, antiGravitySpeed: -0.25, waterSpeed: -0.5, airSpeed: 0.25, acceleration: 0, weight: -0.25, landHandling: -0.25, antiGravityHandling: 0, waterHandling: -0.5, airHandling: 0, traction: 0.25, miniTurbo: 0.25, src: 'https://i.postimg.cc/mkTzqLW1/Cushion.png' } ,
                                    { name:'Blue Standard', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src: 'https://i.postimg.cc/8zcWNzJh/Blue-Standard.png' } ,
                                    { name:'Hot Monster', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: -0.5, acceleration: -0.5, weight: 0.5, landHandling: -0.75, antiGravityHandling: -0.75, waterHandling: -0.5, airHandling: -0.5, traction: 0.5, miniTurbo: -0.25, src: 'https://i.postimg.cc/qMM6xvG9/Hot-Monster.png' } ,
                                    { name:'Azure Roller', landSpeed: -0.5, antiGravitySpeed: -0.5, waterSpeed: 0, airSpeed: 0, acceleration: 0.5, weight: -0.5, landHandling: 0.25, antiGravityHandling: 0.25, waterHandling: 0.25, airHandling: 0.25, traction: -0.25, miniTurbo: 0.75, src: 'https://i.postimg.cc/YCPF9BYT/Azure-Roller.png' } ,
                                    { name:'Crimson Slim', landSpeed: 0.25, antiGravitySpeed: 0.5, waterSpeed: -0.25, airSpeed: -0.25, acceleration: -0.5, weight: 0, landHandling: 0.25, antiGravityHandling: 0, waterHandling: 0.25, airHandling: 0.25, traction: -1, miniTurbo: -0.25, src: 'https://i.postimg.cc/cHy8R7Dm/Crimson-Slim.png' } ,
                                    { name:'Cyber Slick', landSpeed: 0.5, antiGravitySpeed: 0.5, waterSpeed: -0.75, airSpeed: -0.75, acceleration: -0.75, weight: 0.25, landHandling: -0.25, antiGravityHandling: -0.25, waterHandling: -0.75, airHandling: -0.5, traction: -1.25, miniTurbo: -0.75, src: 'https://i.postimg.cc/26QL2qMf/Cyber-Slick.png' } ,
                                    { name:'Retro Off-Road', landSpeed: 0.25, antiGravitySpeed: 0, waterSpeed: 0.25, airSpeed: -0.5, acceleration: -0.25, weight: 0.25, landHandling: -0.5, antiGravityHandling: -0.25, waterHandling: -0.5, airHandling: -0.5, traction: 0.25, miniTurbo: -0.5, src: 'https://i.postimg.cc/rshmP597/Retro-Off-Road.png' } ,
                                    { name:'Gold Tires', landSpeed: 0.5, antiGravitySpeed: -0.25, waterSpeed: 0, airSpeed: -0.25, acceleration: -1, weight: 0.5, landHandling: -0.25, antiGravityHandling: -0.5, waterHandling: -0.25, airHandling: -0.75, traction: -0.75, miniTurbo: -0.75, src: 'https://i.postimg.cc/bYR2nt1x/Gold-Tires.png' } ,
                                    { name:'GLA Tires', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src: 'https://i.postimg.cc/6qz2xkBj/GLA-Tires.png' } ,
                                    { name:'Triforce Tires', landSpeed: 0.25, antiGravitySpeed: 0, waterSpeed: 0.25, airSpeed: -0.5, acceleration: -0.25, weight: 0.25, landHandling: -0.5, antiGravityHandling: -0.25, waterHandling: -0.5, airHandling: -0.5, traction: 0.25, miniTurbo: -0.5, src: 'https://i.postimg.cc/JzHnpDHd/Triforce-Tires.png' } ,
                                    { name:'Ancient Tires', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: -0.5, acceleration: -0.5, weight: 0.5, landHandling: -0.75, antiGravityHandling: -0.75, waterHandling: -0.5, airHandling: -0.5, traction: 0.5, miniTurbo: -0.25, src: 'https://i.postimg.cc/jdZNp75x/Ancient-Tires.png' } ,
                                    { name:'Leaf Tires', landSpeed: -0.25, antiGravitySpeed: 0, waterSpeed: -0.25, airSpeed: -0.25, acceleration: 0.25, weight: -0.5, landHandling: 0, antiGravityHandling: 0.25, waterHandling: 0, airHandling: -0.25, traction: -0.5, miniTurbo: 0.5, src: 'https://i.postimg.cc/pXGhGMGy/Leaf-Tires.png' }
                        ] ,
            gliders:    [           { name:'Super Glider', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0,                         landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src:                               'https://i.postimg.cc/Kj8yKwyg/Super-Glider.png' } ,
                                    { name:'Cloud Glider', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: 0, airSpeed: -0.25, acceleration: 0.25, weight: -0.25, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0.25, traction: 0, miniTurbo: 0.25, src: 'https://i.postimg.cc/c1hxsMNn/Cloud-Glider.png' } ,
                                    { name:'Wario Wing', landSpeed: 0, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: 0, weight: 0.25, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0, traction: -0.25, miniTurbo: 0, src: 'https://i.postimg.cc/DfxhVvqQ/Wario-Wing.png' } ,
                                    { name:'Waddle Wing', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src: 'https://i.postimg.cc/MH3J15W3/Waddle-Wing.png' } ,
                                    { name:'Peach Parasol', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: -0.25, acceleration: 0.25, weight: 0, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0.25, traction: -0.25, miniTurbo: 0.25, src: 'https://i.postimg.cc/gJdpprSs/Peach-Parasol.png' } ,
                                    { name:'Parachute', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: 0, airSpeed: -0.25, acceleration: 0.25, weight: -0.25, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0.25, traction: 0, miniTurbo: 0.25, src: 'https://i.postimg.cc/WbfsZNzp/Parachute.png' } ,
                                    { name:'Parafoil', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: -0.25, acceleration: 0.25, weight: 0, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0.25, traction: -0.25, miniTurbo: 0.25, src: 'https://i.postimg.cc/sgkynT5t/Parafoil.png' } ,
                                    { name:'Flower Glider', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: 0, airSpeed: -0.25, acceleration: 0.25, weight: -0.25, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0.25, traction: 0, miniTurbo: 0.25, src: 'https://i.postimg.cc/1tc9VDnb/Flower-Glider.png' } ,
                                    { name:'Bowser Kite', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: -0.25, acceleration: 0.25, weight: 0, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0.25, traction: -0.25, miniTurbo: 0.25, src: 'https://i.postimg.cc/CLyGgqbk/Bowser-Kite.png' } ,
                                    { name:'Plane Glider', landSpeed: 0, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: 0, weight: 0.25, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0, traction: -0.25, miniTurbo: 0, src: 'https://i.postimg.cc/4d5gxZjg/Plane-Glider.png' } ,
                                    { name:'MKTV Parafoil', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: -0.25, acceleration: 0.25, weight: 0, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0.25, traction: -0.25, miniTurbo: 0.25, src: 'https://i.postimg.cc/x1JnywNv/MKTV-Parafoil.png' } ,
                                    { name:'Gold Glider', landSpeed: 0, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: 0, weight: 0.25, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0, traction: -0.25, miniTurbo: 0, src: 'https://i.postimg.cc/prWPfyKr/Gold-Glider.png' } ,
                                    { name:'Hylian Kite', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src: 'https://i.postimg.cc/Xqs4Q3g8/Hylian-Kite.png' } ,
                                    { name:'Paraglider', landSpeed: 0, antiGravitySpeed: 0.25, waterSpeed: -0.25, airSpeed: 0, acceleration: 0, weight: 0.25, landHandling: 0, antiGravityHandling: -0.25, waterHandling: 0.25, airHandling: 0, traction: -0.25, miniTurbo: 0, src: 'https://i.postimg.cc/FK0vw0Z1/Paraglider.png' } ,
                                    { name:'Paper Glider', landSpeed: -0.25, antiGravitySpeed: 0.25, waterSpeed: 0, airSpeed: -0.25, acceleration: 0.25, weight: -0.25, landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0.25, traction: 0, miniTurbo: 0.25, src: 'https://i.postimg.cc/X7vVXGVD/Paper-Glider.png' }
                        ] ,
            
            currentCharacter: {     name:'default', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0,                               landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src:                               'https://i.postimg.cc/k5zZzVpq/Question-Mark.png' 
                              } ,
            currentBody:      {     name:'default', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0,                               landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src:                               'https://i.postimg.cc/k5zZzVpq/Question-Mark.png' 
                              } ,
            currentWheels:    {     name:'default', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0,                               landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src:                               'https://i.postimg.cc/k5zZzVpq/Question-Mark.png' 
                              } ,
            currentGlider:    {     name:'default', landSpeed: 0, antiGravitySpeed: 0, waterSpeed: 0, airSpeed: 0, acceleration: 0, weight: 0,                               landHandling: 0, antiGravityHandling: 0, waterHandling: 0, airHandling: 0, traction: 0, miniTurbo: 0, src:                               'https://i.postimg.cc/k5zZzVpq/Question-Mark.png' 
                              }
        };
        
        this.selectCharacter = this.selectCharacter.bind(this);
        this.selectBody = this.selectBody.bind(this);
        this.selectWheel = this.selectWheel.bind(this);
        this.selectGlider = this.selectGlider.bind(this);
    }
    
    selectCharacter(character) {
        this.setState({ currentCharacter: character });
    }
    
    selectBody(body) {
        this.setState({ currentBody: body });
    }
    
    selectWheel(wheel) {
        this.setState({ currentWheels: wheel });
    }

    selectGlider(glider) {
        this.setState({ currentGlider: glider });
    }
    
    render() {
        return (
            <div className="container">
                <h1 className="title">Mario Kart Builder</h1>
            
                <div className="selectionContainer">
                    <Characters characters={this.state.characters} addCharacter={this.selectCharacter} />
                    <Bodies bodies={this.state.bodies} addBody={this.selectBody} />
                    <Wheels wheels={this.state.wheels} addWheel={this.selectWheel} />
                    <Gliders gliders={this.state.gliders} addGlider={this.selectGlider} />
                </div>
            
                <Statistics character={this.state.currentCharacter} body={this.state.currentBody} wheels={this.state.currentWheels} glider={this.state.currentGlider} />
            </div>
        );
    }

}

export default App;